/**
 * Pure, browser-safe parser and validator for game achievements manifests.
 * The manifest is generated by the engine (AchievementManager::manifest_json)
 * and placed beside game.js on wasm builds.
 */

/**
 * @typedef {{ id: string, name: string, description: string, hidden: boolean }} CatalogEntry
 * @typedef {{ slug: string, title: string, achievements: CatalogEntry[] }} GameCatalog
 */

/**
 * One game's manifest text → [{id, name, description, hidden}], validated: an array with at
 * least one entry; every entry an object whose id, name and description are strings (id and
 * name non-empty) and whose hidden is a boolean; ids unique. Anything else throws an Error that
 * names `slug` — the file is the engine's own output, so a bad one is a build failure, never
 * something to render around.
 */
export function parseGameCatalog(text, slug) {
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (error) {
    throw new Error(`Game manifest for ${slug} is not valid JSON: ${error.message}`);
  }

  if (!Array.isArray(parsed)) {
    throw new Error(`Game manifest for ${slug} must be an array`);
  }

  if (parsed.length === 0) {
    throw new Error(`Game manifest for ${slug} must have at least one entry`);
  }

  const seenAchievementIds = new Set();
  const achievements = [];

  for (const entry of parsed) {
    if (!entry || typeof entry !== "object" || Array.isArray(entry)) {
      throw new Error(`Game manifest for ${slug} contains an entry that is not an object`);
    }

    if (typeof entry.id !== "string" || entry.id.trim() === "") {
      throw new Error(`Game manifest for ${slug} contains an entry with a missing or empty id`);
    }

    if (typeof entry.name !== "string" || entry.name.trim() === "") {
      throw new Error(`Game manifest for ${slug} contains an entry with a missing or empty name`);
    }

    if (typeof entry.description !== "string") {
      throw new Error(`Game manifest for ${slug} contains an entry with a missing or non-string description`);
    }

    if (typeof entry.hidden !== "boolean") {
      throw new Error(`Game manifest for ${slug} contains an entry with a non-boolean hidden flag`);
    }

    if (seenAchievementIds.has(entry.id)) {
      throw new Error(`Game manifest for ${slug} contains duplicate achievement id "${entry.id}"`);
    }

    seenAchievementIds.add(entry.id);
    achievements.push({
      id: entry.id,
      name: entry.name,
      description: entry.description,
      hidden: entry.hidden,
    });
  }

  return achievements;
}

/**
 * The catalogs a page embedded on its board element as `data-catalogs` — the JSON of the
 * frontmatter's readGameCatalogs() output — or [] when the element is missing, the attribute is
 * absent, or it does not parse. The board then falls back to unlocks-only game groups, and the
 * console says why: a silent fallback would look like a site with almost no achievements.
 * @returns {GameCatalog[]}
 */
export function readEmbeddedCatalogs(element) {
  const text = element?.dataset?.catalogs;
  if (!text) return [];
  try {
    const parsed = JSON.parse(text);
    return Array.isArray(parsed) ? parsed : [];
  } catch (error) {
    console.warn("The embedded game catalogs did not parse; the board shows unlocks only.", error);
    return [];
  }
}
