"""Derived views computed from canonical data (never hand-edited; regenerated by build.py)."""
from . import keys


def menu_by_day(menu):
    """Invert meal keys: {dayKey: {slot: {mealId, menu, cookExtra}}} — the workbook's Menu sheet."""
    result = {day_key: {} for day_key in keys.DAY_KEY_ORDER}
    for meal in menu["meals"]:
        for day_key in meal["days"]:
            result[day_key][meal["slot"]] = {"mealId": meal["id"], "menu": meal["menu"], "cookExtra": meal["cookExtra"]}
    return {day_key: {slot: slots.get(slot) for slot in keys.MEAL_SLOT_ORDER} for day_key, slots in result.items()}


def block_focus_grid(days):
    """{dayKey: {focusBlockKey: focus}} — the data set's per-block focus grid (empty cells on neutral data)."""
    return {day_key: dict(days["days"][day_key].get("blockFocus") or {}) for day_key in days["order"]}


IMPORT_ACTIVITY_FIELDS = ("id", "title", "dayKey", "block", "priority", "categories", "flexibility", "timing")


def default_import_document(data):
    """The data set as an import document (data/schema/import.schema.json, version 2) — the example document
    (applied on the Assistant page). On the neutral canonical data this is FortKnight's short example: empty
    readable lists and a review line telling the person what to do; on the workbook example overlay it is the
    workbook itself (its machine sections). Deterministic (no importedAt) so the bundle hash stays stable."""
    days, blocks = data["days"], data["blocks"]
    carries_schedule = bool(data["activities"]["activities"]) or any(days["days"][day_key].get("blockFocus") for day_key in days["order"])
    if not carries_schedule:
        return {
            "schemaVersion": 2,
            "source": {"kind": "other", "description": "FortKnight's empty example — replace it with the import document your assistant wrote from your calendar, planner or task list (docs/importers.md)"},
            "commitments": [],
            "tasks": [],
            "skipped": [],
            "review": [
                "This is the shape, not your schedule: `commitments` are timed things (appointments, lessons, work or school hours), `tasks` have a day but no clock time, `skipped` is what your assistant saw and left out (and why), `review` is its summary so you can check the list is complete.",
                "Ask your assistant for yours, paste or upload it here, then Apply.",
            ],
            "notes": ["Generated by scripts/build.py from the neutral canonical data."],
        }
    return {
        "schemaVersion": 2,
        "source": {"kind": "xlsx", "description": "FortKnight.xlsx workbook example: block focus grid (days.json), fixed activities (activities.json), block layout (blocks.json)"},
        "commitments": [],
        "tasks": [],
        "skipped": [],
        "review": ["Generated by scripts/build.py from the workbook example set (examples/workbook) — Apply it to use the workbook's block focus grid and fixed activities as your own."],
        "standingAppointments": [],
        "fixedActivities": [{field: activity[field] for field in IMPORT_ACTIVITY_FIELDS} for activity in data["activities"]["activities"]],
        # The data set's menu meals ride along under the reserved `meals` (menuId added), so a person who applies the
        # workbook example gets its menu line on their day pages.
        "meals": [{"menuId": menu_id, **{field: meal[field] for field in ("id", "slot", "mealKey", "days", "menu", "cookExtra") if field in meal}} for menu_id, menu in sorted(data["menus"].items()) for meal in menu["meals"]],
        "blocks": [{"key": block_key, **{field: blocks["blocks"][block_key][field] for field in ("start", "end", "durationMinutes", "carriesFocus")}} for block_key in blocks["order"]],
        "blockFocusGrid": block_focus_grid(days),
        "appointmentBlocks": {day_key: days["days"][day_key]["appointmentBlock"] for day_key in days["order"]},
        "notes": [],
    }


def _meals_by_slot_and_key(menu):
    return {(meal["slot"], meal["mealKey"]): meal for meal in menu["meals"]}


def _resolve_meal_prep_targets(activity, meals_lookup):
    targets = []
    for reference in activity["detail"].get("mealRefs", []):
        meal = meals_lookup.get((reference["slot"], reference["mealKey"]))
        targets.append({
            "slot": reference["slot"],
            "mealKey": reference["mealKey"],
            "days": reference["days"],
            "mealId": meal["id"] if meal else None,
            "menu": meal["menu"] if meal else None,
        })
    return targets


def _activity_sort_key(activity):
    start = activity["timing"]["timeStart"] if activity["timing"] else "99:99"
    return (activity["priority"], start, activity.get("sourceRow", 0))


def plan_by_day(data, menu=None):
    """Per day: focus, appointment block, menu (when a menu is given), and each block with focus/meal hints/activities."""
    meals_lookup = _meals_by_slot_and_key(menu) if menu else {}
    per_day_menu = menu_by_day(menu) if menu else {day_key: {slot: None for slot in keys.MEAL_SLOT_ORDER} for day_key in data["days"]["order"]}
    activities_by_day_and_block = {}
    for activity in data["activities"]["activities"]:
        activities_by_day_and_block.setdefault((activity["dayKey"], activity["block"]), []).append(activity)

    plan = {}
    for day_key in data["days"]["order"]:
        day = data["days"]["days"][day_key]
        blocks = []
        for block_key in data["blocks"]["order"]:
            block = data["blocks"]["blocks"][block_key]
            activities = sorted(activities_by_day_and_block.get((day_key, block_key), []), key=_activity_sort_key)
            blocks.append({
                "block": block_key,
                "label": block["label"],
                "start": block["start"],
                "end": block["end"],
                "focus": (day.get("blockFocus") or {}).get(block_key),
                "isAppointmentBlock": block_key == day["appointmentBlock"],
                "mealPrimary": block["mealPrimary"],
                "mealSecondary": block["mealSecondary"],
                "activities": [
                    {
                        "id": activity["id"],
                        "title": activity["title"],
                        "priority": activity["priority"],
                        "categories": activity["categories"],
                        "flexibility": activity["flexibility"],
                        "timing": activity["timing"],
                        "detail": activity["detail"],
                        "mealPrepTargets": _resolve_meal_prep_targets(activity, meals_lookup),
                    }
                    for activity in activities
                ],
            })
        plan[day_key] = {
            "dayKey": day_key,
            "index": day["index"],
            "week": day["week"],
            "label": day["label"],
            "mainFocus": day.get("mainFocus"),
            "appointmentBlock": day["appointmentBlock"],
            "menu": per_day_menu[day_key],
            "blocks": blocks,
        }
    return plan
